### ISSUE TITLE
Drupal and REST

### ISSUE THREAD

**Issue by smoking-peanuts** [codeforgreenville/UpstateEvents#15]
Wanted to know how Drupal setup was going?

**Comment by smoking-peanuts** [comment]
@allella So how is the Rest API going.. anything that I can do to help?

**Comment by allella** [comment]
@smoking-peanuts I got the basic schema setup in Drupal 8. I tried to import all 35 records, but the Feeds module has some bugs.

I'll see if I can import it in. If not then I may need a hand with data entry.

**Comment by allella** [comment]
@smoking-peanuts The feeds module is "not stable". I'm going to try to create records using the REST API to see how that works.

https://www.drupal.org/node/2022803

**Comment by allella** [comment]
@smoking-peanuts 

Alright, the REST API is up and working.

Drupal 8 is still a bit buggy and incomplete, so I spent about 3 hours trying to deal with Drupal 8 instability and 30 minutes to actually configure things and figure how to add an update a record. I actually had to reinstall Drupal, so the work I did last night setting up the Organization fields is gone, but that's only about 5-10 minutes of work.

Anyway, I was able to create (POST) a test organization with a Name (aka title) and a status (aka field_situation) and then update the title using a (PATCH).

This means I'll be able to programmatically POST all 35 organizations, so no need to type them in.

## Viewing the Organization
Again, there's only two fields on the organization at the moment, but I'll add them soon.

Here's the human readable web page.
http://greenville.orangecoat.net/node/1

You'll need to install the Dev HTTP Client plugin for Chrome to see the REST response for the organization.  I know that may not make sense, but if you go to the "Using the REST API" section of https://drupalize.me/blog/201401/introduction-restful-web-services-drupal-8 then he has screen shots and it's rather easy.

## Other Notes
The update command in REST is usually PUT, but Drupal is using PATCH instead because of technical reasons which are way over my head.   So, GET, POST, PATCH, DELETE are the 4 commands that correspond to view, add, update, delete.

It's currently necessary to use Content-Type: application/hal+json for POST and PATCH due to the issues I described here https://www.drupal.org/node/1964034#comment-9619331

**Comment by allella** [comment]
## Doing a Simple REST GET Method

So, once the Dev HTTP Client plugin is installed in Google Chrome you can just fill in the values shown in the screenshot. However, I'll have to give you the full username and password.

Request URL is greenville.orangecoat.net/node/1

Accept: application/json
PHP_AUTH_USER: {ask Jim}
PHP_AUTH_PW: {ask Jim}

![rest-api-organization-get-example](https://cloud.githubusercontent.com/assets/1777776/6182983/9c838ff4-b31c-11e4-8d55-1ece8eb2f6cc.png)

This should yield a JSON object response with organization and Drupal data.

```
{
    "nid": [
        {
            "value": "1"
        }
    ],
    "uuid": [
        {
            "value": "4e6c3292-a8f0-4b6e-a30f-15a0d8589877"
        }
    ],
    "vid": [
        {
            "value": "1"
        }
    ],
    "type": [
        {
            "target_id": "organization"
        }
    ],
    "langcode": [
        {
            "value": "en"
        }
    ],
    "title": [
        {
            "value": "Code For Greenville 2"
        }
    ],
    "uid": [
        {
            "target_id": "2"
        }
    ],
    "status": [
        {
            "value": "1"
        }
    ],
    "created": [
        {
            "value": "1423793426"
        }
    ],
    "changed": [
        {
            "value": "1423806628"
        }
    ],
    "promote": [
        {
            "value": "0"
        }
    ],
    "sticky": [
        {
            "value": "0"
        }
    ],
    "revision_timestamp": [
        {
            "value": "1423793454"
        }
    ],
    "revision_uid": [
        {
            "target_id": "2"
        }
    ],
    "revision_log": [
        {
            "value": ""
        }
    ],
    "path": [
        {
            "alias": null,
            "pid": null
        }
    ],
    "field_situation": [
        {
            "value": "active"
        }
    ]
}
```

**Comment by allella** [comment]
### Helpful Tutorials (Tuts) and Documentation
http://tntfoss-vivekvpandya.rhcloud.com/node/40
https://drupalize.me/blog/201401/introduction-restful-web-services-drupal-8
http://build2be.com/content/state-rest-headless-drupal-8
https://www.drupal.org/node/2098511

### JSON Validation Tool
http://pro.jsonlint.com/

### Jim Summarizing the State of Drupal 8 PATCH
https://www.drupal.org/node/1964034#comment-9619331

**Comment by smoking-peanuts** [comment]
Hey Jim,
I didn't read all of your e-mail but I will get to it Sunday and start seeing how I can participate.. Thanks so much for getting drupal and the REST api setup..-landon 

     On Friday, February 13, 2015 1:27 AM, Jim Ciallella <notifications@github.com> wrote:
   

 
Helpful Tutorials (Tuts) and Documentation
http://tntfoss-vivekvpandya.rhcloud.com/node/40
https://drupalize.me/blog/201401/introduction-restful-web-services-drupal-8
http://build2be.com/content/state-rest-headless-drupal-8
https://www.drupal.org/node/2098511
JSON Validation Tool
http://pro.jsonlint.com/
Jim Summarizing the State of Drupal 8 PATCH
https://www.drupal.org/node/1964034#comment-9619331—
